name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Build local (en el runner), sin Oryx
      - name: Install & Build
        working-directory: site
        run: |
          npm ci
          npm run build

      # Deploy artefactos ya construidos → saltamos Oryx
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_PEBBLE_05FD4B603 }}
          action: upload
          # IMPORTANTES para evitar Oryx:
          skip_app_build: true
          app_location: site                 # raíz de la app
          app_artifact_location: site/build  # carpeta con el build
          skip_api_build: true
          api_location: ""                   # sin API
          data_api_location: ""              # evita chequear 'swa-db-connections'
          production_branch: main
