name: Build & Push backend to ACR
on:
  workflow_dispatch: {}         # permite Run workflow manual
  push:
    branches: [ main, master ]  # por si tu rama por defecto no es main
    paths:
      - 'apps/backend/**'       # incluye subcarpetas y archivos nuevos
      - '.github/workflows/build-backend.yml'  # si solo cambias el workflow
  pull_request:
    branches: [ main, master ]
    paths:
      - 'apps/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ACR_LOGIN_SERVER: clientexacr.azurecr.io
      IMAGE_NAME: backend
      IMAGE_TAG: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./apps/backend
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
